/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.io.FileInputStream;
import java.io.IOException;
import java.util.Scanner;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import model.AlgoritmoCuadratico;
import model.ConstanteMultiplicativoSC;
import model.ProductosMediosNC;

/**
 *
 * @author joang
 */
public class UInterface extends javax.swing.JFrame {
    ProductosMediosNC pmedios;
    AlgoritmoCuadratico cuadratico;
    ConstanteMultiplicativoSC cmult;

    /**
     * Creates new form UInterface
     */
    public UInterface() {
        initComponents();
        clabel.setVisible(false);
        glabel.setVisible(false);
        ctext.setVisible(false);
        gtext.setVisible(false);
        
        rpm.setSelected(true);
        
        pmedios = new ProductosMediosNC();
        cuadratico = new AlgoritmoCuadratico();
        cmult = new ConstanteMultiplicativoSC();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        aGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        rpm = new javax.swing.JRadioButton();
        rc = new javax.swing.JRadioButton();
        rcm = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        x0label = new javax.swing.JLabel();
        x0text = new javax.swing.JTextField();
        x1label = new javax.swing.JLabel();
        x1text = new javax.swing.JTextField();
        digitoslabel = new javax.swing.JLabel();
        digitostext = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        itmaxtext = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        filename = new javax.swing.JTextField();
        clabel = new javax.swing.JLabel();
        ctext = new javax.swing.JTextField();
        glabel = new javax.swing.JLabel();
        gtext = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        calcular = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Números PseudoAleatorios");
        setLocationByPlatform(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Algoritmo", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        aGroup.add(rpm);
        rpm.setText("Productos Medios");
        rpm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rpmActionPerformed(evt);
            }
        });

        aGroup.add(rc);
        rc.setText("Cuadratico");
        rc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rcActionPerformed(evt);
            }
        });

        aGroup.add(rcm);
        rcm.setText("Constante Multiplicativo");
        rcm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rcmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rpm)
                .addGap(18, 18, 18)
                .addComponent(rc)
                .addGap(18, 18, 18)
                .addComponent(rcm)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rpm)
                    .addComponent(rc)
                    .addComponent(rcm))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        x0label.setText("X0:");
        x0label.setToolTipText("");

        x1label.setText("X1:");

        x1text.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                x1textActionPerformed(evt);
            }
        });

        digitoslabel.setText("D:");

        jLabel4.setText("itmax:");

        jLabel1.setText("Nombre de archivo:");

        clabel.setText("c:");
        clabel.setToolTipText("");

        glabel.setText("g:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(x0label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(x0text, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(clabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ctext, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(78, 78, 78)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(x1label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(x1text, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(67, 67, 67)
                        .addComponent(digitoslabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(digitostext, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(65, 65, 65)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(itmaxtext, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(glabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(gtext, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filename, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(x0label)
                    .addComponent(x0text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(x1label)
                    .addComponent(x1text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(digitoslabel)
                    .addComponent(digitostext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(itmaxtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(filename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clabel)
                    .addComponent(ctext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(glabel)
                    .addComponent(gtext, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 292, Short.MAX_VALUE)
        );

        calcular.setText("Calcular");
        calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcularActionPerformed(evt);
            }
        });

        textArea.setEditable(false);
        textArea.setColumns(20);
        textArea.setRows(5);
        jScrollPane1.setViewportView(textArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 774, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(calcular)
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addGap(18, 18, 18)
                .addComponent(calcular)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public String readFile(String arch){
        String text = "";
        
        try{
            Scanner lector = new Scanner(new FileInputStream("src/outputs/" + arch + ".txt"));
            while(lector.hasNext())
                text += lector.nextLine() + "\n";
            
        }catch(IOException e){
            text = "Can't Open File";
            JOptionPane.showMessageDialog(this, "Error al abrir el archivo", "Error", 0);
        }
        return text;
    }
    
    private boolean PMIsEmpty(){
        return x0text.getText().isEmpty() || x1text.getText().isEmpty() || 
               digitostext.getText().isEmpty() || itmaxtext.getText().isEmpty()|| 
               filename.getText().isEmpty();
    }
    
    private boolean RCIsEmpty(){
        return x0text.getText().isEmpty() || x1text.getText().isEmpty() || 
               digitostext.getText().isEmpty() || itmaxtext.getText().isEmpty()|| 
               filename.getText().isEmpty() || ctext.getText().isEmpty() ||
               gtext.getText().isEmpty();
    }
    
    private boolean RCMIsEmpty(){
        return x0text.getText().isEmpty() || x1text.getText().isEmpty() || 
               digitostext.getText().isEmpty() || itmaxtext.getText().isEmpty()|| 
               filename.getText().isEmpty() || ctext.getText().isEmpty();
    }
    
    private void rpmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rpmActionPerformed
        x0label.setText("X0:");
        x1label.setText("X1:");
        digitoslabel.setText("D:");
        clabel.setVisible(false);
        glabel.setVisible(false);
        ctext.setVisible(false);
        gtext.setVisible(false);
        clean();
    }//GEN-LAST:event_rpmActionPerformed

    private void x1textActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_x1textActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_x1textActionPerformed
    
    private void clean(){
        x0text.setText("");
        x1text.setText("");
        digitostext.setText("");
        ctext.setText("");
        gtext.setText("");
        filename.setText("");
        itmaxtext.setText("");
    }
    
    private void calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcularActionPerformed
        if (!rpm.isSelected() && !rc.isSelected() && !rcm.isSelected()) {
            JOptionPane.showMessageDialog(this, "Seleccione un Algoritmo.", "Error", 0);
        }else if (rpm.isSelected()) {
            if (PMIsEmpty())
                JOptionPane.showMessageDialog(this, "Rellene todos los campos.");
            else{
//                pmedios.calcular(digitostext.getText(), x1text.getText(), x0text.getText(), itmaxtext.getText(), filename.getText());
                textArea.setText(readFile(filename.getText()));
            }
        }else if (rc.isSelected()){
            if (RCIsEmpty())
                JOptionPane.showMessageDialog(this, "Rellene todos los campos.");
            else{
//                cuadratico.calcular(x1text.getText(), digitostext.getText(), ctext.getText(), gtext.getText(), x0text.getText(), itmaxtext.getText(), filename.getText());
                textArea.setText(readFile(filename.getText()));
            }
        }else if (rcm.isSelected()){
            if (RCMIsEmpty())
                JOptionPane.showMessageDialog(this, "Rellene todos los campos.");
            else{
//                cmult.Calcular(x0text.getText(), x1text.getText(), digitostext.getText(), ctext.getText(), itmaxtext.getText(), filename.getText());
                textArea.setText(readFile(filename.getText()));
            }
        }
        
        
    }//GEN-LAST:event_calcularActionPerformed

    private void rcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rcActionPerformed
        x0label.setText("X0:");
        x1label.setText("a:");
        digitoslabel.setText("b:");
        clabel.setVisible(true);
        glabel.setVisible(true);
        ctext.setVisible(true);
        gtext.setVisible(true);
        clean();
    }//GEN-LAST:event_rcActionPerformed

    private void rcmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rcmActionPerformed
        x0label.setText("X0:");
        x1label.setText("a:");
        digitoslabel.setText("c:");
        clabel.setText("m:");
        clabel.setVisible(true);
        glabel.setVisible(false);
        ctext.setVisible(true);
        gtext.setVisible(false);
        clean();
    }//GEN-LAST:event_rcmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UInterface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UInterface().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup aGroup;
    private javax.swing.JButton calcular;
    private javax.swing.JLabel clabel;
    private javax.swing.JTextField ctext;
    private javax.swing.JLabel digitoslabel;
    private javax.swing.JTextField digitostext;
    private javax.swing.JTextField filename;
    private javax.swing.JLabel glabel;
    private javax.swing.JTextField gtext;
    private javax.swing.JTextField itmaxtext;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rc;
    private javax.swing.JRadioButton rcm;
    private javax.swing.JRadioButton rpm;
    private javax.swing.JTextArea textArea;
    private javax.swing.JLabel x0label;
    private javax.swing.JTextField x0text;
    private javax.swing.JLabel x1label;
    private javax.swing.JTextField x1text;
    // End of variables declaration//GEN-END:variables
}
